# Generated by Django 2.1.7 on 2025-08-15 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=32)),
                ('CNname', models.CharField(default='', max_length=32)),
                ('Tel', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('Seat', models.CharField(choices=[('KS-Plant5', 'KS-Plant5'), ('KS-Plant3', 'KS-Plant3'), ('KS-Plant2', 'KS-Plant2'), ('CQ', 'CQ'), ('CD', 'CD'), ('TPE', 'TPE'), ('PCP', 'PCP'), ('LKE', 'LKE')], default='KS-Plant5', max_length=108)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.IntegerField(choices=[(1, '测试部门'), (2, '开发部门'), (3, 'PM'), (4, '其它部门')], default=1, verbose_name='部门')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_SVPuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'UserInfo',
                'verbose_name_plural': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(blank=True, max_length=30, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('icon', models.CharField(default='el-icon-menu', max_length=32)),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('path', models.CharField(blank=True, max_length=128, null=True, verbose_name='路由路径')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend01.Menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu_title', models.CharField(max_length=32, unique=True)),
                ('url', models.CharField(max_length=128, unique=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend01.Menu')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('perms', models.ManyToManyField(to='backend01.Permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Photo',
            field=models.ManyToManyField(blank=True, related_name='imgs', to='backend01.Imgs', verbose_name='图片表'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.ManyToManyField(to='backend01.Role'),
        ),
    ]
