# Generated by Django 2.1.7 on 2025-08-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend01', '0002_auto_20250815_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Photo',
            field=models.ManyToManyField(blank=True, to='backend01.Imgs', verbose_name='图片表'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
