# Generated by Django 2.1.7 on 2025-08-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend01', '0003_auto_20250818_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='components',
            field=models.CharField(default='', max_length=128),
        ),
    ]
