# Generated by Django 2.1.7 on 2025-08-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='柜体名称')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('description', models.CharField(blank=True, max_length=2000, verbose_name='描述')),
                ('rows', models.PositiveIntegerField(default=5, verbose_name='行数')),
                ('cols', models.PositiveIntegerField(default=6, verbose_name='列数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '柜体',
                'verbose_name_plural': '柜体',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CabinetGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='行')),
                ('col', models.PositiveIntegerField(verbose_name='列')),
                ('position', models.CharField(help_text='例如：A1, B2等', max_length=10, verbose_name='位置编号')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '空闲'), (1, '使用中'), (2, '预定中'), (3, '拿取保留中')], verbose_name='状态')),
                ('Customer', models.CharField(choices=[('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('T88', 'T88'), ('T89', 'T89')], max_length=20, verbose_name='客戶別')),
                ('ProCode', models.CharField(blank=True, max_length=100, verbose_name='客戶ProCode')),
                ('CampalCode', models.CharField(blank=True, max_length=100, verbose_name='CampalCode')),
                ('Brow_at', models.DateTimeField(blank=True, null=True, verbose_name='留樣日期')),
                ('BrowReson', models.CharField(blank=True, max_length=2000, verbose_name='留樣原因')),
                ('Take_at', models.DateTimeField(blank=True, null=True, verbose_name='拿取日期')),
                ('TakeReson', models.CharField(blank=True, max_length=2000, verbose_name='拿取原因')),
                ('Back_at', models.DateTimeField(blank=True, null=True, verbose_name='放回日期')),
                ('user', models.CharField(blank=True, max_length=20, verbose_name='借用人（工号）')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('notes', models.CharField(blank=True, max_length=2000, verbose_name='備注')),
                ('creator', models.CharField(blank=True, max_length=20, verbose_name='创建人工号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='IntelligentCabinet.Cabinet', verbose_name='所属柜体')),
            ],
            options={
                'verbose_name': '柜格',
                'verbose_name_plural': '柜格',
                'ordering': ['cabinet', 'row', 'col'],
            },
        ),
        migrations.CreateModel(
            name='GridRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('reserve', '预定'), ('use', '使用'), ('release', '释放'), ('keep', '拿取保留中')], max_length=20, verbose_name='操作')),
                ('old_status', models.PositiveSmallIntegerField(choices=[(0, '空闲'), (1, '使用中'), (2, '预定中'), (3, '拿取保留中')], verbose_name='原状态')),
                ('new_status', models.PositiveSmallIntegerField(choices=[(0, '空闲'), (1, '使用中'), (2, '预定中'), (3, '拿取保留中')], verbose_name='新状态')),
                ('Customer', models.CharField(blank=True, max_length=100, verbose_name='客戶別')),
                ('ProCode', models.CharField(blank=True, max_length=100, verbose_name='客戶ProCode')),
                ('CampalCode', models.CharField(blank=True, max_length=100, verbose_name='CampalCode')),
                ('Brow_at', models.DateTimeField(blank=True, null=True, verbose_name='留樣日期')),
                ('BrowReson', models.CharField(blank=True, max_length=2000, verbose_name='留樣原因')),
                ('Take_at', models.DateTimeField(blank=True, null=True, verbose_name='拿取日期')),
                ('TakeReson', models.CharField(blank=True, max_length=2000, verbose_name='拿取原因')),
                ('Back_at', models.DateTimeField(blank=True, null=True, verbose_name='放回日期')),
                ('user', models.CharField(blank=True, max_length=20, verbose_name='借用人（工号）')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('notes', models.CharField(blank=True, max_length=2000, verbose_name='備注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='IntelligentCabinet.CabinetGrid', verbose_name='柜格')),
            ],
            options={
                'verbose_name': '柜格记录',
                'verbose_name_plural': '柜格记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cabinetgrid',
            unique_together={('cabinet', 'position')},
        ),
    ]
